### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by OlehBabiak** [OlehBabiak/travel-app#6]
- [x] the block with filters contains:

- search box
- two selects to select duration and level

- [x] When entering values ​​in the search field or changing filters, the corresponding cards should be displayed

- [x] the travel card contains the following elements:

- picture
- the name of the trip
- travel information - duration and complexity
- travel price
- button leading to the travel page
![image](https://user-images.githubusercontent.com/66703682/173101537-5ac2a6b0-2267-43a8-bcdc-0bcb37101408.png)

**Comment by Sir-Rumeh** [comment]
Are we working with an API ?

**Comment by OlehBabiak** [comment]
done
